### ISSUE TITLE
it doesn't work on moodle 3.2

### ISSUE THREAD

**Issue by ghost** [rezaies/moodle-calendartype_jalali#1]
it doesn't work on moodle 3.2 and there's not any calendar type in the user setting!

**Comment by rezaies** [comment]
Hi Nima,
It is tested with Moodle 3.2 and it works.
You should be able to change your calendar by opening the user menu (at top left or right) and going to "Preferences > Calendar preferences"

**Comment by ghost** [comment]
Hi rezaies
Are u sure? because after i've seen this problem, I installed moodle 3.1 and jalali-calendar is working. I don't see any calendar over the user settings. As u see there's the screenshot in the attachment

![1](https://cloud.githubusercontent.com/assets/18008545/21021283/0809c604-bd8d-11e6-94dd-dd19c0fae42d.jpg)

**Comment by rezaies** [comment]
Yep :)
Please refer to my previous comment again. It is a little bit different on 3.2.

>  ... by opening the user menu (at top left or right) and going to "Preferences > Calendar preferences"

You can see that it works at http://demo.foodle.org/ on Moodle 3.2

**Comment by ghost** [comment]
oh, i didn't see that new part. thank u so much.
so what should i do if i wanna set this preference for all of my users to default?

**Comment by rezaies** [comment]
Site administration ► Appearance ► Calendar
