### ISSUE TITLE
User profile fields date picker bug

### ISSUE THREAD

**Issue by fazelfarajzade** [rezaies/moodle-calendartype_jalali#2]
When I add a new User profile field of type Date/Time . and I change site calendar . when I want to pick a date in Edit profile page it automatically changes after save .

I`m using moodle 3.3 and calander version : 

`$plugin->version    = 2017030200;`
`$plugin->requires   = 2013110100; `
`$plugin->component  = 'calendartype_jalali'; `
`$plugin->release    = '1.1 for Moodle 2.6 onwards';`
`$plugin->dependencies = array('calendartype_gregorian' => ANY_VERSION);`
`$plugin->maturity   = MATURITY_STABLE;`

**Comment by rezaies** [comment]
I'm closing this issue as it is not about the Jalali plugin itself. The bug is in the date/time profile field plugin.
