### ISSUE TITLE
Error setting enrollment start and end dates

### ISSUE THREAD

**Issue by paymanzafar** [rezaies/moodle-calendartype_jalali#3]
Hi,
I installed this calendar on Moodle 3.5 recently. Today I started using Moodle and I tried to enroll some students in a class with enrollment start and end times. After I saved the times, I found that they are reset to 1 Farvardin 1278.
To solve the problem, I changed my calendar preferences to Gregorian, and revised the dates. It was correct.
Again, I changed the calendar to Persian. The enrollment dates were correct. I clicked on the save button without any changes. The dates again reset to 1 Farvardin 1278.
I have screen captures before and after pressing "save changes" button, but it seems there is no place I can upload them here.

**Comment by rezaies** [comment]
Hi Payman,
I could not replicate the issue you described.
Could you please provide replication instructions using bullet points.

**Comment by rezaies** [comment]
Closing this as I can not replicate the issue.
If you think that the issue can be reproduced, please create a new issue providing as much detail as you can.

**Comment by z-avanes** [comment]
Hi
I have same problem
After clicked on the save button date set to 1 Farvardin 1278
