### ISSUE TITLE
PHP error when displaying dates in Forum

### ISSUE THREAD

**Issue by andrewnicols** [rezaies/moodle-calendartype_jalali#4]
Just saw this when displaying dates in the forum:

`Warning: A non-numeric value encountered in /Users/nicols/Sites/moodles/im/moodle/calendar/type/jalali/classes/structure.php on line 356
`

**Comment by rezaies** [comment]
Thank you, Andrew, for reporting this.
The issue you reported is already fixed in the latest version.
I am closing this now.
