### ISSUE TITLE
Not working on 3.8.1

### ISSUE THREAD

**Issue by iamnavid** [rezaies/moodle-calendartype_jalali#6]
I've installed it and changed my preferred calendar to Persian but nothing happens. I'm using Moodle 3.8.1+.

Regards

**Comment by sparse91** [comment]
Git version is working on Moodle 3.9.

**Comment by asrmodiriat** [comment]
برای این که تقویم درست کار کند 
می بایست ترجیحات تقویم کاربر نیز شمسی باشد
پس از همان ابتدای راه اندازی مودل تقویم فارسی نصب شود و تقویم سایت و ترجیحات پیش فرض کاربران بر روی تقویم شمسی قرار گیرد..

- آقای شمیم این بخش رو باید تصحیح کنند که وقتی کاربری ترجیح تقویمش میلادی است و تقویم مودل شمسی این خطا رخ ندهد

**Comment by rezaies** [comment]
I am closing this as not a bug.
Installing a new calendar type should NOT automatically change the calendar type that is used by the existing users.
I understand you might want this to happen, but what you think should happen can be considered as a serious regression to others.
